name: Build Android Library

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build:
    name: android main on linux
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "11"

      - name: Install required packages
        run: sudo apt install -y gperf yasm nasm autogen autopoint meson ninja-build

      - name: Run the build script
        run: |
          ./android.sh \
          --enable-gpl \
          --enable-android-media-codec \
          --enable-android-zlib \
          --disable-arm-v7a \
          --disable-arm-v7a-neon \
          --disable-x86
          
          echo FFMPEG_KIT_VERSION=$(grep '#define FFMPEG_KIT_VERSION' android/ffmpeg-kit-android-lib/src/main/cpp/ffmpegkit.h | grep -Eo '\".*\"' | sed -e 's/\"//g') >> $GITHUB_ENV

      - name: Create Release
        if: ${{ github.event_name == 'workflow_dispatch' }}
        uses: softprops/action-gh-release@v1
        with:
          body: The changelog is on the [original repository](https://github.com/arthenica/ffmpeg-kit/tag/v${{ env.FFMPEG_KIT_VERSION }}).
          files: prebuilt/bundle-android-aar/ffmpeg-kit/ffmpeg-kit.aar
          tag_name: v${{ env.FFMPEG_KIT_VERSION }}
